.TH EMACS 1
.SH "NAME"
emacs \- a screen editor
.SH "SYNOPSIS"
emacs files...
.SH "DESCRIPTION"
Unix
.I
Emacs
is a text editor styled after the editors of the same name that exist
on ITS, Twenex and Multics.
Invoking
.I
emacs
with a list of files causes
.I
emacs
to start up and do a visit-file on each of the named files.
For more information, read the manual.
.SH "FILES"
/usr/local/lib/emacs/*
.SH "ENVIRONMENT"
EPATH is a path used when locating files with the load command.
.SH "SEE ALSO"
The Unix Emacs manual, which should be on /usr/local/doc/emacs.press
on your favorite VAX at CMUCSD.  Copies can also be obtained from Howard
Wactlers Secretary.  Those not at CMUCSD can send netmail to Gosling@CMUA
asking for a copy.
.SH "BUGS"
Not bloody likely.
.SH HISTORY
.TP
08-Jan-81  James Gosling (jag) at Carnegie-Mellon University
Created.
