@b[^@@]@\set-mark
@b[^A]@\beginning-of-line
@b[^B]@\backward-character
@b[^C]@\exit-emacs
@b[^D]@\delete-next-character
@b[^E]@\end-of-line
@b[^F]@\forward-character
@b[^G]@\illegal-operation
@b[^H]@\delete-previous-character
@b[^I]@\self-insert
@b[^J]@\newline-and-indent
@b[^K]@\kill-to-end-of-line
@b[^L]@\redraw-display
@b[^M]@\newline
@b[^N]@\next-line
@b[^O]@\newline-and-backup
@b[^P]@\previous-line
@b[^Q]@\quote-character
@b[^R]@\search-reverse
@b[^S]@\search-forward
@b[^T]@\transpose-characters
@b[^U]@\argument-prefix
@b[^V]@\next-page
@b[^W]@\delete-to-killbuffer
@b[^X]@\^X-prefix
@b[^X-^B]@\list-buffers
@b[^X-^C]@\exit-emacs
@b[^X-^D]@\describe-word-in-buffer
@b[^X-^E]@\compile-it
@b[^X-^F]@\write-file-exit
@b[^X-^I]@\insert-file
@b[^X-^M]@\write-modified-files
@b[^X-^N]@\next-error
@b[^X-^O]@\use-old-buffer
@b[^X-^R]@\read-file
@b[^X-^S]@\write-current-file
@b[^X-^V]@\visit-file
@b[^X-^W]@\write-named-file
@b[^X-^X]@\exchange-dot-and-mark
@b[^X-^Z]@\shrink-window
@b[^X-!]@\execute-monitor-command
@b[^X-(]@\start-remembering
@b[^X-)]@\stop-remembering
@b[^X-1]@\delete-other-windows
@b[^X-2]@\split-current-window
@b[^X-b]@\switch-to-buffer
@b[^X-d]@\delete-window
@b[^X-e]@\execute-keyboard-macro
@b[^X-m]@\smail
@b[^X-n]@\next-window
@b[^X-p]@\previous-window
@b[^X-r]@\rmail
@b[^X-z]@\enlarge-window
@b[^Y]@\yank-from-killbuffer
@b[^Z]@\scroll-one-line-up
@b[ESC]@\ESC-prefix
@b[ESC-^C]@\exit-emacs
@b[ESC-^V]@\page-next-window
@b[ESC-^W]@\delete-region-to-buffer
@b[ESC-^Y]@\yank-buffer
@b[ESC-ESC]@\execute-mlisp-line
@b[ESC-^^]@\case-region-invert
@b[ESC-!]@\line-to-top-of-window
@b[ESC-,]@\beginning-of-window
@b[ESC--]@\meta-minus
@b[ESC-.]@\end-of-window
@b[ESC-0..ESC-9]@\meta-digit
@b[ESC-<]@\beginning-of-file
@b[ESC->]@\end-of-file
@b[ESC-?]@\apropos
@b[ESC-[]@\backward-paragraph
@b[ESC-]]@\forward-paragraph
@b[ESC-^]@\case-word-invert
@b[ESC-a]@\backward-sentence
@b[ESC-b]@\backward-word
@b[ESC-d]@\delete-next-word
@b[ESC-e]@\forward-sentence
@b[ESC-f]@\forward-word
@b[ESC-h]@\delete-previous-word
@b[ESC-j]@\indent-C-procedure
@b[ESC-l]@\case-word-lower
@b[ESC-q]@\query-replace-string
@b[ESC-r]@\replace-string
@b[ESC-u]@\case-word-upper
@b[ESC-v]@\previous-page
@b[ESC-x]@\execute-extended-command
@b[ESC-z]@\scroll-one-line-down
@b[^_]@\return-to-monitor
@b[ ..,]@\self-insert
@b[-]@\minus
@b[.../]@\self-insert
@b[0..9]@\digit
@b[:..~]@\self-insert
@b[^?]@\delete-previous-character
