(progn
    (use-abbrev-table "rlisp")
    (define-local-abbrev "lp" "lisp procedure")
    (define-local-abbrev "bs" "begin scalar")
    (use-abbrev-table "geom")

    ; keyword templates
    (define-local-abbrev "lp" "lisp procedure")
    (define-local-abbrev "bs" "begin scalar")

    ; View management commands.
    (define-local-abbrev "nw" "newWindow")
    (define-local-abbrev "gw" "getWindow")
    (define-local-abbrev "tv" "TopView")
    (define-local-abbrev "sv" "SideView")
    (define-local-abbrev "fv" "FrontView")
    (define-local-abbrev "pv" "ProjView")
    (define-local-abbrev "ptv" "ProjTopView")

    ; Coordinate systems.
    (define-local-abbrev "cc" "CurrentCoords")
    (define-local-abbrev "vc" "ViewCoords")
    (define-local-abbrev "gc" "GlobalCoords!*")
    (define-local-abbrev "nc" "newCoords();")
    (define-local-abbrev "t2" "translate2D(")
    (define-local-abbrev "t3" "translate3D(")
    (define-local-abbrev "tx" "translateX(")
    (define-local-abbrev "ty" "translateY(")
    (define-local-abbrev "tz" "translateZ(")
    (define-local-abbrev "r2" "rotate2D(")
    (define-local-abbrev "rx" "rotateX(")
    (define-local-abbrev "ry" "rotateY(")
    (define-local-abbrev "rz" "rotateZ(")
    (define-local-abbrev "s3" "scale3D(")
    (define-local-abbrev "sx" "scaleX(")
    (define-local-abbrev "sy" "scaleY(")
    (define-local-abbrev "sz" "scaleZ(")
    (define-local-abbrev "pc" "pushCoords();")
    (define-local-abbrev "ppc" "popCoords();")
    (define-local-abbrev "ldc" "loadCoords(")
    (define-local-abbrev "chc" "chgCoords(")

    ; Vector math.
    (define-local-abbrev "vl" "vecLength")
    (define-local-abbrev "uv" "unitVec")
    (define-local-abbrev "va" "vecAdd(")
    (define-local-abbrev "v2p" "vecFrom2Pts(")
    (define-local-abbrev "vm" "vecMul(")
    (define-local-abbrev "vi" "vecInterp(")
    (define-local-abbrev "p2o" "P2Origin")

    ; Lines.
    (define-local-abbrev "lpa" "linePtAngle(")
    (define-local-abbrev "lpv" "linePtVec(")
    (define-local-abbrev "l2p" "lineThru2Pts(")
    (define-local-abbrev "lpp" "linePtParallel(")
    (define-local-abbrev "lv" "lineVertical(")
    (define-local-abbrev "lh" "lineHorizontal(")
    (define-local-abbrev "lol" "lineOffsetFromLine(")
    (define-local-abbrev "p2l" "ptIntersect2Lines(")
    (define-local-abbrev "rl" "reverseLine")
    (define-local-abbrev "ppl" "projectPtOntoLine(")
    (define-local-abbrev "dpl" "distPtLine(")
    (define-local-abbrev "dol" "dirOfLine")
    (define-local-abbrev "drp" "dirPerpLine")

    ; Arcs.
    (define-local-abbrev "a3l" "arcTan3Lines(")
    (define-local-abbrev "a2l" "arcRadTan2Lines(")
    (define-local-abbrev "a3p" "arcThru3Pts(")
    (define-local-abbrev "aece" "arcEndCenterEnd(")
    (define-local-abbrev "aal" "arcRadTanToArcAndLine(")
    (define-local-abbrev "roa" "radiusOfArc")
    (define-local-abbrev "coa" "centerOfArc")

    ; Curves and surfaces.
    (define-local-abbrev "prof" "profile(")
    (define-local-abbrev "ccon" "crvConcat(")
    (define-local-abbrev "ptl" "ptListFromCrv")
    (define-local-abbrev "symx" "symmetricX")
    (define-local-abbrev "symy" "symmetricY")
    (define-local-abbrev "swp" "sweepCrvPerpToCrv(")
    (define-local-abbrev "prpc" "projPtOntoCyl(")
    (define-local-abbrev "prlc" "projLnSegOntoCyl(")

    ; Primitive solids.
    (define-local-abbrev "rpp" "rectParallelepiped")
    (define-local-abbrev "box" "Box")
    (define-local-abbrev "raw" "RtAngleWedge")
    (define-local-abbrev "p8v" "Polyhedron8vertices") 
    (define-local-abbrev "arb8" "Polyhedron8vertices") 
    (define-local-abbrev "p7v" "Polyhedron7vertices")
    (define-local-abbrev "arb7" "Polyhedron7vertices")
    (define-local-abbrev "p6v" "Polyhedron6vertices")
    (define-local-abbrev "arb6" "Polyhedron6vertices")
    (define-local-abbrev "p5v" "Polyhedron5vertices") 
    (define-local-abbrev "arb5" "Polyhedron5vertices") 
    (define-local-abbrev "p4v" "Polyhedron4Vertices")
    (define-local-abbrev "arb4" "Polyhedron4Vertices")
    (define-local-abbrev "rcc" "RtCirCyl")
    (define-local-abbrev "trc" "TruncRtAngleCone")
    (define-local-abbrev "rec" "RtEllipCyl")
    (define-local-abbrev "tec" "TruncEllipCone")
    (define-local-abbrev "sph" "Sphere")
    (define-local-abbrev "ella" "EllipsoidFromAxes")
    (define-local-abbrev "ellf" "EllipsoidFromFocii")
    (define-local-abbrev "tor" "Torus")
    (define-local-abbrev "ars" "ArbSurface")

    ; Display datastructure access fns.
    (define-local-abbrev "cs" "valueCell CurrentScreen!*")
    (define-local-abbrev "cw" "valueCell CurrentWindow!*")
    (define-local-abbrev "cv" "valueCell CurrentView!*")
    ; 
    (define-local-abbrev "gsda" "gScreenDevAssigned")
    (define-local-abbrev "gswl" "gScreenWindowList")
    (define-local-abbrev "gsvar" "gScreenVars")
    ; 
    (define-local-abbrev "gwsl" "gWindowScreenList")
    (define-local-abbrev "gwvl" "gWindowViewList")
    (define-local-abbrev "gwvar" "gWindowVars")
    (define-local-abbrev "gwps" "gWindowPerScreen")
    (define-local-abbrev "gwwm" "gWindowWindMat")
    (define-local-abbrev "gwvm" "gWindowViewMat")
    (define-local-abbrev "gwvp" "gWindowViewPort")
    (define-local-abbrev "gwm" "gWindowMenu")
    ; 
    (define-local-abbrev "vbwl" "viewBuffWindList")
    (define-local-abbrev "vbol" "viewBuffObjList")
    (define-local-abbrev "vbvar" "viewBuffVars")
    (define-local-abbrev "vbps" "viewBuffPerScreen")
    (define-local-abbrev "vbc" "viewBuffCoords")
    ; 
    (define-local-abbrev "docv" "dispObjCoordView")
    (define-local-abbrev "dovl" "dispObjViewList")
    (define-local-abbrev "dops" "dispObjPerScreen")
    (define-local-abbrev "dov" "dispObjVis")
    (define-local-abbrev "doc" "dispObjColor")
    (define-local-abbrev "dol" "dispObjLbl")
    (define-local-abbrev "doll" "dispObjLblLoc")

    (novalue)
)
