; Create key bindings for mhe.
; 
(progn ch
    (save-excursion
	(temp-use-buffer "mh-temp")
	(setq needs-checkpointing 0)
	(define-keymap "&mh-keymap")
	(use-local-map "&mh-keymap")
	(setq ch 0)
	(while (<= ch 127)
	    (if (= (global-binding-of ch) "self-insert")
		(local-bind-to-key "&mh-summary" ch))
	    (setq ch (+ ch 1))
	)
	(setq ch '0')
	(while (<= ch '9')
	    (local-bind-to-key "illegal-operation" ch)
	    (setq ch (+ ch 1))
	)
	(local-bind-to-key "&mh-rmm" "d")
	(local-bind-to-key "&mh-refile" "^")
	(local-bind-to-key "&mh-refile" "s")
	(local-bind-to-key "&mh-rerefile" "!")
	(local-bind-to-key "&mh-previous-line" "p")
	(local-bind-to-key "&mh-next-line" "n")
	(local-bind-to-key "&mh-undo" "u")
	(local-bind-to-key "&mh-show" "t")
	(local-bind-to-key "&mh-repl" "r")
	(local-bind-to-key "&mh-comp" "c")
	(local-bind-to-key "&mh-comp" "m")
	(local-bind-to-key "&mh-forw" "f")
	(local-bind-to-key "&mh-inc" "i")
	(local-bind-to-key "&mh-pack-folder" "\^X\^P")
	(local-bind-to-key "&mh-close-folder" "\^X\^C")
	(local-bind-to-key "&mh-scan" "\^X\^S")
	(local-bind-to-key "&mh-folders" "\^X\^F")
    )
)
