(defun 
    (send-ps
	(save-excursion
	    (if (! prefix-argument-provided)
		(Mark-Whole-Buffer)
	    )
	    (copy-region-to-buffer "ToPS")
	    (temp-use-buffer "ToPS")
	    (Mark-Whole-Buffer)
	    (filter-region "cat >/dev/ttyhb")
	    (temp-use-buffer "Kill buffer")
	    (erase-buffer)
	)
    )
    (ps300-mode
	(utah-c-mode)
	(save-excursion
	    (temp-use-buffer "Scratch")
	    (set-mark)
	    (filter-region "stty 9600 cooked -tabs -nl >/dev/ttyhb")
	)
	(setq comment-begin "{ ")
	(setq comment-end " }")
	(setq comment-start "{")
	(setq comment-continuation 0)
	(setq mode-string "PS300")
	(local-bind-to-key "send-ps" "\^Z\e")
	(use-abbrev-table "PS300")
	(novalue)
    )
)
(auto-execute "ps300-mode" "*.ps")
(auto-execute "ps300-mode" "*.300")
(novalue)
